name: pokegame
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  cloud_firestore: ^5.6.7
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  get_it: ^8.0.3
  http: ^1.3.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  lottie: ^3.3.1
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/notification/
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 100

  integrations:
    flutter_svg: true
    lottie: true